### ISSUE TITLE
*ОПАСНОСТЬ* Третья лаба может быть затоплена потоком дерьма от %ПРЕПОДНЭЙМ%!!!

### ISSUE THREAD

**Issue by kpa6uu** [DronCode/HomeWork_Algorithms#2]
*СПАСАЙТЕ ДЕТЕЙ И ЖЕНЩИН!*

Надо поправить косяк, где идут строки:
min(bi + ci)
max(bi+ci)

У тебя идёт суммирование минимумов массивов, а нужно сами массивы прогнать через for, попутно складывая их значения, и найти либо максимальную получившуюся сумму, либо минимальную.
http://pastebin.com/LCG3tUz3

Там снизу есть пример.

**Comment by DronCode** [comment]
Ахуеть брат, ты спасаешь. Спасиб
#TeamWork

**Comment by DronCode** [comment]
Fixed.
